export const SEATING_CHART = [
  { firstName: "Yaw", lastName: "Amankwa Agyekum", table: 8, partyID: "33" },
  { firstName: "Min", lastName: "Baek", table: 3, partyID: "10" },
  { firstName: "Brendan", lastName: "Bong", table: 8, partyID: "36" },
  { firstName: "Stanley", lastName: "Chen", table: 1, partyID: "6" },
  { firstName: "Jasmine", lastName: "Cheng", table: 1, partyID: "1" },
  { firstName: "Francis", lastName: "Cheng", table: 2, partyID: "1" },
  { firstName: "Alex", lastName: "Chick", table: 7, partyID: "29" },
  { firstName: "Vincent", lastName: "Chick", table: 7, partyID: "29" },
  { firstName: "Nicole", lastName: "Chin", table: 5, partyID: "17" },
  { firstName: "Nathan", lastName: "Chiu", table: 6, partyID: "23" },
  { firstName: "Christina", lastName: "Chong", table: 6, partyID: "24" },
  { firstName: "Ivan", lastName: "Chow", table: 6, partyID: "21" },
  { firstName: "Christina", lastName: "Chu Chiu", table: 6, partyID: "23" },
  { firstName: "Jason", lastName: "Cihelka", table: 8, partyID: "30" },
  { firstName: "Ahmed", lastName: "Ghazi", table: 1, partyID: "5" },
  { firstName: "Sean", lastName: "Gilmour", table: 9, partyID: "39" },
  { firstName: "Meghan", lastName: "Hoang", table: 1, partyID: "6" },
  { firstName: "Young ", lastName: "Hong", table: 1, partyID: "2" },
  { firstName: "Braden", lastName: "Kabeary", table: 6, partyID: "22" },
  { firstName: "Brishti", lastName: "Kayastha", table: 5, partyID: "19" },
  { firstName: "Laura", lastName: "Krejci", table: 3, partyID: "11" },
  { firstName: "Vaclav", lastName: "Krejci", table: 3, partyID: "11" },
  { firstName: "Meagan", lastName: "Krejci", table: 4, partyID: "11" },
  { firstName: "Yam", lastName: "Lai", table: 2, partyID: "1" },
  { firstName: "Matthew", lastName: "Lai", table: 2, partyID: "1" },
  { firstName: "Aimee", lastName: "Lai", table: 2, partyID: "1" },
  { firstName: "YanYan 恩恩", lastName: "Lai 賴", table: 2, partyID: "1" },
  { firstName: "Miu 淼", lastName: "Lai 賴", table: 2, partyID: "1" },
  { firstName: "YamLoi 任箂", lastName: "Lai 賴", table: 2, partyID: "1" },
  { firstName: "Lorinda", lastName: "Laturnas", table: 5, partyID: "20" },
  { firstName: "Sophearith", lastName: "Lay", table: 1, partyID: "3" },
  { firstName: "Alex", lastName: "Leaf", table: 3, partyID: "9" },
  { firstName: "George", lastName: "Lepine", table: 3, partyID: "7" },
  { firstName: "Kathryn", lastName: "Lepine", table: 3, partyID: "9" },
  { firstName: "Jonathan", lastName: "Lepine", table: 3, partyID: "10" },
  { firstName: "Susan", lastName: "Lepine", table: 4, partyID: "12" },
  { firstName: "Paulette", lastName: "Lepine", table: 4, partyID: "13" },
  { firstName: "Claire", lastName: "Lepine", table: 4, partyID: "14" },
  { firstName: "Roger", lastName: "Lepine", table: 4, partyID: "15" },
  { firstName: "Robert", lastName: "Lepine", table: 4, partyID: "15" },
  { firstName: "Theo", lastName: "Lepine", table: 4, partyID: "15" },
  { firstName: "Victoria", lastName: "Lepine", table: 4, partyID: "16" },
  { firstName: "Jake", lastName: "Lepine", table: 6, partyID: "15" },
  { firstName: "Yakov", lastName: "Lipkovich", table: 8, partyID: "31" },
  { firstName: "Jonathan", lastName: "Lo", table: 9, partyID: "40" },
  { firstName: "Richard", lastName: "Long", table: 9, partyID: "37" },
  { firstName: "Jon", lastName: "Luong", table: 8, partyID: "32" },
  { firstName: "Michelle", lastName: "Ma", table: 6, partyID: "25" },
  { firstName: "Derek", lastName: "Mah", table: 6, partyID: "25" },
  { firstName: "Chris", lastName: "McCaw", table: 7, partyID: "27" },
  { firstName: "Brogan", lastName: "Mueller", table: 5, partyID: "18" },
  { firstName: "Annie", lastName: "Nguyen", table: 9, partyID: "40" },
  { firstName: "Mack", lastName: "Page", table: 5, partyID: "18" },
  { firstName: "Ken", lastName: "Peralta", table: 8, partyID: "34" },
  { firstName: "Gerald", lastName: "Priestley", table: 4, partyID: "14" },
  { firstName: "Fathia", lastName: "Rezwan", table: 7, partyID: "27" },
  { firstName: "Wanda", lastName: "Sakura", table: 3, partyID: "7" },
  { firstName: "Pat", lastName: "Sakura", table: 3, partyID: "7" },
  { firstName: "Gene", lastName: "Sakura", table: 3, partyID: "7" },
  { firstName: "Brad", lastName: "Screen", table: 7, partyID: "28" },
  { firstName: "Kimberly", lastName: "Screen", table: 7, partyID: "28" },
  { firstName: "Andrew", lastName: "Shannon", table: 5, partyID: "20" },
  { firstName: "Christopher", lastName: "Smith", table: 4, partyID: "16" },
  { firstName: "Chris", lastName: "Smith", table: 7, partyID: "26" },
  { firstName: "Tyeesha", lastName: "Street", table: 9, partyID: "39" },
  { firstName: "Connie", lastName: "Suen", table: 2, partyID: "8" },
  { firstName: "Danny", lastName: "Suen", table: 2, partyID: "8" },
  { firstName: "Elaine", lastName: "Sun", table: 9, partyID: "38" },
  { firstName: "Paul", lastName: "Tong", table: 2, partyID: "1" },
  { firstName: "Anthony", lastName: "Tran", table: 8, partyID: "35" },
  { firstName: "Sharon", lastName: "Tse", table: 1, partyID: "3" },
  { firstName: "Tim", lastName: "Tse", table: 1, partyID: "4" },
  { firstName: "Kloria", lastName: "Wen", table: 7, partyID: "26" },
  { firstName: "Doyle", lastName: "Wolff", table: 5, partyID: "19" },
  { firstName: "Angela", lastName: "Wong", table: 6, partyID: "22" },
  { firstName: "Mike", lastName: "Wong", table: 6, partyID: "24" },
  { firstName: "Vanna", lastName: "Wong", table: 7, partyID: "29" },
  { firstName: "Angela", lastName: "Wu", table: 9, partyID: "37" },
  { firstName: "Rieko", lastName: "Yamai", table: 8, partyID: "30" },
  { firstName: "May", lastName: "Yiu", table: 1, partyID: "4" },
  { firstName: "Sven", lastName: "Zhang", table: 9, partyID: "38" },
];
