export const SEATING_CHART = [
  { firstName: "Jasmine", lastName: "Cheng", table: 1, partyID: "" },
  { firstName: "Young ", lastName: "Hong", table: 1, partyID: "" },
  { firstName: "Sharon", lastName: "Tse", table: 1, partyID: "" },
  { firstName: "Sophearith", lastName: "Lay", table: 1, partyID: "" },
  { firstName: "May", lastName: "Yiu", table: 1, partyID: "" },
  { firstName: "Tim", lastName: "Tse", table: 1, partyID: "" },
  { firstName: "Ahmed", lastName: "Ghazi", table: 1, partyID: "" },
  { firstName: "Stanley", lastName: "Chen", table: 1, partyID: "" },
  { firstName: "Meghan", lastName: "Hoang", table: 1, partyID: "" },
  { firstName: "Yam", lastName: "Lai", table: 2, partyID: "" },
  { firstName: "Paul", lastName: "Tong", table: 2, partyID: "" },
  { firstName: "Connie", lastName: "Suen", table: 2, partyID: "" },
  { firstName: "Danny", lastName: "Suen", table: 2, partyID: "" },
  { firstName: "Matthew", lastName: "Lai", table: 2, partyID: "" },
  { firstName: "Francis", lastName: "Cheng", table: 2, partyID: "" },
  { firstName: "Aimee", lastName: "Lai", table: 2, partyID: "" },
  { firstName: "YanYan 恩恩", lastName: "Lai 賴", table: 2, partyID: "" },
  { firstName: "Miu 淼", lastName: "Lai 賴", table: 2, partyID: "" },
  { firstName: "YamLoi 任箂", lastName: "Lai 賴", table: 2, partyID: "" },
  { firstName: "George", lastName: "Lepine", table: 3, partyID: "" },
  { firstName: "Wanda", lastName: "Sakura", table: 3, partyID: "" },
  { firstName: "Pat", lastName: "Sakura", table: 3, partyID: "" },
  { firstName: "Gene", lastName: "Sakura", table: 3, partyID: "" },
  { firstName: "Kathryn", lastName: "Lepine", table: 3, partyID: "" },
  { firstName: "Alex", lastName: "Leaf", table: 3, partyID: "" },
  { firstName: "Jonathan", lastName: "Lepine", table: 3, partyID: "" },
  { firstName: "Min", lastName: "Baek", table: 3, partyID: "" },
  { firstName: "Laura", lastName: "Krejci", table: 3, partyID: "" },
  { firstName: "Vaclav", lastName: "Krejci", table: 3, partyID: "" },
  { firstName: "Meagan", lastName: "Krejci", table: 4, partyID: "" },
  { firstName: "Susan", lastName: "Lepine", table: 4, partyID: "" },
  { firstName: "Paulette", lastName: "Lepine", table: 4, partyID: "" },
  { firstName: "Claire", lastName: "Lepine", table: 4, partyID: "" },
  { firstName: "Gerald", lastName: "Priestley", table: 4, partyID: "" },
  { firstName: "Roger", lastName: "Lepine", table: 4, partyID: "" },
  { firstName: "Robert", lastName: "Lepine", table: 4, partyID: "" },
  { firstName: "Theo", lastName: "Lepine", table: 4, partyID: "" },
  { firstName: "Victoria", lastName: "Lepine", table: 4, partyID: "" },
  { firstName: "Christopher", lastName: "Smith", table: 4, partyID: "" },
  { firstName: "Nicole", lastName: "Chin", table: 5, partyID: "" },
  { firstName: "Brogan", lastName: "Mueller", table: 5, partyID: "" },
  { firstName: "Mack", lastName: "Page", table: 5, partyID: "" },
  { firstName: "Brishti", lastName: "Kayastha", table: 5, partyID: "" },
  { firstName: "Doyle", lastName: "Wolff", table: 5, partyID: "" },
  { firstName: "Lorinda", lastName: "Laturnas", table: 5, partyID: "" },
  { firstName: "Andrew", lastName: "Shannon", table: 5, partyID: "" },
  { firstName: "Jake", lastName: "Lepine", table: 6, partyID: "" },
  { firstName: "Ivan", lastName: "Chow", table: 6, partyID: "" },
  { firstName: "Angela", lastName: "Wong", table: 6, partyID: "" },
  { firstName: "Braden", lastName: "Kabeary", table: 6, partyID: "" },
  { firstName: "Nathan", lastName: "Chiu", table: 6, partyID: "" },
  { firstName: "Christina", lastName: "Chu Chiu", table: 6, partyID: "" },
  { firstName: "Christina", lastName: "Chong", table: 6, partyID: "" },
  { firstName: "Mike", lastName: "Wong", table: 6, partyID: "" },
  { firstName: "Michelle", lastName: "Ma", table: 6, partyID: "" },
  { firstName: "Derek", lastName: "Mah", table: 6, partyID: "" },
  { firstName: "Kloria", lastName: "Wen", table: 7, partyID: "" },
  { firstName: "Chris", lastName: "Smith", table: 7, partyID: "" },
  { firstName: "Fathia", lastName: "Rezwan", table: 7, partyID: "" },
  { firstName: "Chris", lastName: "McCaw", table: 7, partyID: "" },
  { firstName: "Brad", lastName: "Screen", table: 7, partyID: "" },
  { firstName: "Kimberly", lastName: "Screen", table: 7, partyID: "" },
  { firstName: "Alex", lastName: "Chick", table: 7, partyID: "" },
  { firstName: "Vanna", lastName: "Wong", table: 7, partyID: "" },
  { firstName: "Vincent", lastName: "Chick", table: 7, partyID: "" },
  { firstName: "Jason", lastName: "Cihelka", table: 8, partyID: "" },
  { firstName: "Rieko", lastName: "Yamai", table: 8, partyID: "" },
  { firstName: "Yakov", lastName: "Lipkovich", table: 8, partyID: "" },
  { firstName: "Jon", lastName: "Luong", table: 8, partyID: "" },
  { firstName: "Yaw", lastName: "Amankwa Agyekum", table: 8, partyID: "" },
  { firstName: "Ken", lastName: "Peralta", table: 8, partyID: "" },
  { firstName: "Anthony", lastName: "Tran", table: 8, partyID: "" },
  { firstName: "Brendan", lastName: "Bong", table: 8, partyID: "" },
  { firstName: "Richard", lastName: "Long", table: 9, partyID: "" },
  { firstName: "Angela", lastName: "Wu", table: 9, partyID: "" },
  { firstName: "Sven", lastName: "Zhang", table: 9, partyID: "" },
  { firstName: "Elaine", lastName: "Sun", table: 9, partyID: "" },
  { firstName: "Sean", lastName: "Gilmour", table: 9, partyID: "" },
  { firstName: "Tyeesha", lastName: "Street", table: 9, partyID: "" },
  { firstName: "Annie", lastName: "Nguyen", table: 9, partyID: "" },
  { firstName: "Jonathan", lastName: "Lo", table: 9, partyID: "" },
];
